version: "3.8"

services:
  sentinel-db:
    image: postgres:16
    container_name: sentinel_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sentinel_data
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  metabase:
    image: metabase/metabase:latest
    container_name: sentinel_metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=sentinel_data
      - MB_DB_PORT=5432
      - MB_DB_USER=admin
      - MB_DB_PASS=password123
      - MB_DB_HOST=sentinel-db
    depends_on:
      - sentinel-db
